"""empty message

Revision ID: 679779987c7c
Revises: None
Create Date: 2016-07-10 02:14:13.106623

"""

# revision identifiers, used by Alembic.
revision = '679779987c7c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installations', sa.Column('glassfrogToken', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installations', 'glassfrogToken')
    ### end Alembic commands ###
